# Generated by Django 4.2.4 on 2023-11-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_books_category_publisher_expense_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.publisher'),
        ),
    ]
