# Generated by Django 4.2.4 on 2023-11-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.books'),
        ),
    ]
